ARG DBTS_PATH=/go/src/github.com/cs3238-tsuzu/dash-button-tradfri-switch

FROM golang:1.11 AS build

ARG DBTS_PATH
ENV GO111MODULE=on
COPY . ${DBTS_PATH}
WORKDIR ${DBTS_PATH}

RUN apt-get update && \
    apt-get install -y libpcap0.8-dev && \
    cd canopus/openssl && \
    ./config && \
    make -j2 && \
    touch ../go.mod

RUN go build -o main
COPY ${DBTS_PATH}/main /bin/main

ENTRYPOINT [ "/bin/main" ]
